In [1]:
import numpy as np
import pandas as pd

In [2]:
path = 'ecomm-open-cdp/items_ohe_2019_oct.csv'
df = pd.read_csv(path)

In [4]:
df.to_parquet('items_ohe_2019_oct.parquet')

In [5]:
df2 = pd.read_parquet('ecomm-open-cdp/items_ohe_2019_oct.parquet')

In [6]:
df2.head()dd

,Unnamed: 0,accessories.bag,accessories.umbrella,accessories.wallet,apparel.belt,apparel.costume,apparel.dress,apparel.jacket,apparel.jeans,apparel.jumper,...,kids.skates,kids.swing,kids.toys,medicine.tools.tonometer,sport.bicycle,sport.ski,sport.snowboard,sport.tennis,sport.trainer,stationery.cartrige
0,0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False